name: Publish fhEVM Solidity prerelease

on:
  release:
    types: [prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18.x
      - run: cp .env.example .env
      - run: npm ci
      - run: npm run compile
      - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
        with:
          tag: prerelease
          token: ${{ secrets.NPM_TOKEN }}
